export const saved = [
	{
		StudentNo: 'ACES/098/903',
		LastName: 'Uzochi',
		FirstName: 'Joseph',
		OtherName: 'Bibian',
		Gender: 'Female',
		DateOfBirth: '23/01/2020',
		profileImg: require('../assets/images/student.jpg'),
		NationalID: '032',
		StateOfOriginID: '394',
		LGAOfOriginId: '37',
		AdmissionDate: '24/09/2020',
		ClassAdmittedId: '02',
		TermAdmitted: '1',
		YearOfAdmission: '2020',
		CurrentClassId: '092',
		GuardianFirstName: 'Jonah',
		GuardianLastName: 'Uzochi',
		GuardianOtherName: 'Mark',
		GuardianGender: 'Male',
		GuardianPhoneNo: '2348101967324',
		GuardianEmailAddress: 'markjonah@gmail.com',
		GuardianRelationship: 'Father',
		GuardianAddress: 'Charity lane off Mongrove street, woji PH',
		status: 'Uploaded',
		id: 0
	},
	{
		StudentNo: 'ACES/098/903',
		LastName: 'Mavins',
		FirstName: 'John',
		OtherName: 'Ebuca',
		Gender: 'Male',
		DateOfBirth: '23/01/2020',
		profileImg: require('../assets/images/avater.jpg'),
		NationalID: '032',
		StateOfOriginID: '394',
		LGAOfOriginId: '37',
		AdmissionDate: '24/09/2020',
		ClassAdmittedId: '02',
		TermAdmitted: '1',
		YearOfAdmission: '2020',
		CurrentClassId: '092',
		GuardianFirstName: 'Jonah',
		GuardianLastName: 'Uzochi',
		GuardianOtherName: 'Mark',
		GuardianGender: 'Male',
		GuardianPhoneNo: '2348101967324',
		GuardianEmailAddress: 'markjonah@gmail.com',
		GuardianRelationship: 'Father',
		GuardianAddress: 'Charity lane off Mongrove street, woji PH',
		status: 'Waiting',
		id: 1
	},
	{
		StudentNo: 'ACES/098/903',
		LastName: 'Uzochi',
		FirstName: 'Joseph',
		OtherName: 'Bibian',
		Gender: 'Female',
		DateOfBirth: '23/01/2020',
		profileImg: require('../assets/images/student2.png'),
		NationalID: '032',
		StateOfOriginID: '394',
		LGAOfOriginId: '37',
		AdmissionDate: '24/09/2020',
		ClassAdmittedId: '02',
		TermAdmitted: '1',
		YearOfAdmission: '2020',
		CurrentClassId: '092',
		GuardianFirstName: 'Jonah',
		GuardianLastName: 'Uzochi',
		GuardianOtherName: 'Mark',
		GuardianGender: 'Male',
		GuardianPhoneNo: '2348101967324',
		GuardianEmailAddress: 'markjonah@gmail.com',
		GuardianRelationship: 'Father',
		GuardianAddress: 'Charity lane off Mongrove street, woji PH',
		status: 'Waiting',
		id: 3
	},
	{
		StudentNo: 'ACES/098/903',
		LastName: 'Uzochi',
		FirstName: 'Joseph',
		OtherName: 'Bibian',
		Gender: 'Female',
		DateOfBirth: '23/01/2020',
		profileImg: require('../assets/images/student3.jpg'),
		NationalID: '032',
		StateOfOriginID: '394',
		LGAOfOriginId: '37',
		AdmissionDate: '24/09/2020',
		ClassAdmittedId: '02',
		TermAdmitted: '1',
		YearOfAdmission: '2020',
		CurrentClassId: '092',
		GuardianFirstName: 'Jonah',
		GuardianLastName: 'Uzochi',
		GuardianOtherName: 'Mark',
		GuardianGender: 'Male',
		GuardianPhoneNo: '2348101967324',
		GuardianEmailAddress: 'markjonah@gmail.com',
		GuardianRelationship: 'Father',
		GuardianAddress: 'Charity lane off Mongrove street, woji PH',
		status: 'Uploaded',
		id: 4
	},
	{
		StudentNo: 'ACES/098/903',
		LastName: 'Uzochi',
		FirstName: 'Joseph',
		OtherName: 'Bibian',
		Gender: 'Female',
		DateOfBirth: '23/01/2020',
		profileImg: require('../assets/images/student4.jpg'),
		NationalID: '032',
		StateOfOriginID: '394',
		LGAOfOriginId: '37',
		AdmissionDate: '24/09/2020',
		ClassAdmittedId: '02',
		TermAdmitted: '1',
		YearOfAdmission: '2020',
		CurrentClassId: '092',
		GuardianFirstName: 'Jonah',
		GuardianLastName: 'Uzochi',
		GuardianOtherName: 'Mark',
		GuardianGender: 'Male',
		GuardianPhoneNo: '2348101967324',
		GuardianEmailAddress: 'markjonah@gmail.com',
		GuardianRelationship: 'Father',
		GuardianAddress: 'Charity lane off Mongrove street, woji PH',
		status: 'Uploaded',
		id: 5
	},
	{
		StudentNo: 'ACES/098/903',
		LastName: 'Uzochi',
		FirstName: 'Joseph',
		OtherName: 'Bibian',
		Gender: 'Female',
		DateOfBirth: '23/01/2020',
		profileImg: require('../assets/images/student.jpg'),
		NationalID: '032',
		StateOfOriginID: '394',
		LGAOfOriginId: '37',
		AdmissionDate: '24/09/2020',
		ClassAdmittedId: '02',
		TermAdmitted: '1',
		YearOfAdmission: '2020',
		CurrentClassId: '092',
		GuardianFirstName: 'Jonah',
		GuardianLastName: 'Uzochi',
		GuardianOtherName: 'Mark',
		GuardianGender: 'Male',
		GuardianPhoneNo: '2348101967324',
		GuardianEmailAddress: 'markjonah@gmail.com',
		GuardianRelationship: 'Father',
		GuardianAddress: 'Charity lane off Mongrove street, woji PH',
		Status: 'Uploaded',
		id: 6
	}
];

export const stateOfOrigins = [
	{ value: 0, label: "Rivers" },
	{ value: 1, label: "Eboyi" },
	{ value: 2, label: "Abia" },
	{ value: 3, label: "Lagos" },
	{ value: 4, label: "Ibadan" },
	{ value: 5, label: "Benen" },
	{ value: 6, label: "Jigawa" },
	{ value: 7, label: "Platue" },
	{ value: 8, label: "Jos" }
]

export const Nationalites = [
	{ value: 0, label: 'Nigeria' },
	{ value: 1, label: 'Ghana' },
	{ value: 3, label: 'Togo' },
	{ value: 4, label: 'Benen' },
	{ value: 5, label: 'Chad' },
	{ value: 6, label: 'Nigeria' },
	{ value: 7, label: 'Ghana' },
]

export const localgovernments = [
	{ value: 1, label: "zinag" },
	{ value: 1, label: "Ikwere" },
	{ value: 1, label: "Port Harcourt" }
]

export const classes = [
	{ value: 1, label: "Primary 4" },
	{ value: 2, label: "Nursary 1" },
	{ value: 3, label: "Primary 2" },
	{ value: 4, label: "Primary 3" }
]

export const terms = [
	{ value: 1, label: "First Term" },
	{ value: 2, label: "Second Term" },
	{ value: 3, label: "Third Term" }
]